name: call_kit_test_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Networking
  dio: ^5.3.3   # MIT
  http: ^1.1.0 # BSD-3-Clause
  
  #Utils Native Code
  sentry_flutter: ^7.10.1   # MIT
  form_field_validator: ^1.1.0   # MIT
  flutter_translate: ^4.0.4   # MIT
  simple_gravatar: ^1.1.0   # MIT
  dartx: ^1.1.0   # Apache 2
  tuple: ^2.0.0   # BSD
  fluttericon: ^2.0.0   # BSD
  badges: ^3.1.1    # Apache 2
  flutter_launcher_icons: ^0.13.1    # MIT
  flutter_email_sender: 6.0.2    # Apache 2
  flutter_keyboard_visibility: ^5.0.2   # MIT
  cached_network_image: ^3.0.0    # MIT
  quiver: ^3.0.1    # Apache 2
  collection: ^1.17.1 #BSD-3-Clause
  flutter_local_notifications: ^15.1.0+1 #BSD-3-Clause
  mime: ^1.0.1    #BSD-3-Clause
  rive: ^0.11.4 #MIT
# The rive ptt animation is placed here: https://rive.app/community/7117-14684-ptt-button-animation

  #Utils Platform-Specific
  geolocator: ^10.0.1  # MIT
  permission_handler: ^10.0.0    # MIT
  url_launcher: ^6.0.4    # BSD
  package_info_plus: ^4.1.0    # BSD
  device_info_plus: ^9.0.3    # BSD-3-Clause
  file_picker: ^5.3.3    # MIT
  flutter_archive: ^5.0.0    # BSD-3-Clause
  vibration: ^1.7.6    # BSD
  just_audio: any    # Apache 2
  flutter_linkify: ^6.0.0   # MIT
  audioplayers: # MIT
    git:
      url: https://github.com/valeriiaradzivilo/audioplayers.git
      ref: master
      path: packages/audioplayers


  flutter_callkit_incoming: ^2.0.1+2
  uni_links: ^0.5.1 # BSD-2-Clause
  flutter_app_badger: ^1.5.0   # Apache 2
  phone_state: ^1.0.2 # BSD-3-Clause
  flutter_tts: ^3.8.3 # MIT
  validators: ^3.0.0 # MIT
  flutter_native_splash: ^2.3.0    # MIT
  flutter_cache_manager: ^3.3.0    # MIT
  shared_storage: ^0.8.1 # MIT
  aad_oauth: 0.4.4 # MIT

  #Generators
  built_collection: ^5.0.0   # BSD
  freezed_annotation: ^2.2.0 # MIT

  #Logging
  logger: ^2.0.2+1   # MIT

  #Persistence
  shared_preferences: ^2.0.6    # BSD

  #State Management
  provider: ^6.0.2    # MIT

  #Rx
  rxdart: ^0.27.0     # Apache 2
  rx_widgets: ^4.2.1 # BSD-3-Clause

  #UI
  flutter_animate: ^4.1.0 # BSD-3-Clause
  dots_indicator: ^3.0.0    # MIT
  flutter_svg: 2.0.2    # MIT
  bot_toast: ^4.0.1   # Apache 2
  flutter_map: ^6.1.0   # BSD
  flutter_map_marker_popup: ^6.1.2    # BSD
  flutter_map_marker_cluster: ^1.3.0    # BSD
  geocoding: ^2.0.4 # MIT
  # geocoder:  # MIT
  #   git:
  #     url : https://github.com/aloisdeniel/flutter_geocoder.git
  #     ref : master
  latlong2: ^0.9.0    # Apache 2
  auto_size_text: ^3.0.0-nullsafety.0   # MIT
  image_picker: ^1.0.4    # Apache 2
  image_gallery_saver: '^2.0.3'   # MIT
  photo_view: ^0.14.0   # MIT
  video_player: ^2.3.0  # BSD-3-Clause
  chewie: ^1.7.0   # MIT
  crypto: ^3.0.1    # BSD
  proximity_sensor: ^1.0.2
  expand_tap_area: ^1.1.1 # MIT
  sliding_up_panel: ^2.0.0+1 # Unknown (Akshath Jain)
  dropdown_button2: ^2.3.8 # MIT
  reorderable_grid_view: ^2.2.6 #MIT
  responsive_builder: ^0.7.0 #
  giphy_picker: ^3.0.1 # BSD-3 Clause
  any_link_preview: ^3.0.1 # MIT
  animated_text_kit: ^4.2.2 # MIT
  device_preview: ^1.1.0
  infinite_scroll_pagination: ^4.0.0 #MIT
  gap: ^3.0.1 #MIT
  shimmer: ^3.0.0 #BSD-3-Clause
  flutter_chat_bubble: ^2.0.2 # BSD-2-Clause
  flutter_slidable: ^3.0.1 # MIT
  carousel_slider: ^4.2.1 #MIT

  #QR Codes
  qr_flutter: ^4.1.0    # BSD
  qr_code_scanner: ^1.0.1   # BSD
  share_plus: ^7.1.0 # BSD-3-Clause

  #Bluetooth LE
  flutter_blue_plus: 1.31.10 # BSD-3-Clause

  #Internal libraries
  # cornea_dart:
  #   hosted: https://repo.dillonkane.com/artifactory/api/pub/icet-pubdev/
  #   version: 1.0.32838
    ### (Babich) Alternate way, pointing to local Cornea branches.
#    git:
#      url: ssh://git@altssh.bitbucket.org:443/instantconnect/arcus.git
#      path: common/cornea-dart/
#      ref: d03c8b7a
### (Babich) Alternate way, pointing to local path:
    # path: ../arcus/common/cornea-dart/

  json_annotation: ^4.6.0 # BSD-3-Clause
  path_provider: ^2.0.9 # BSD-3-Clause
  battery_plus: ^4.0.2 # BSD-3-Clause
  connectivity_plus: ^4.0.2 # BSD-3-Clause
  wifi_info_plugin_plus: ^2.0.2 # BSD-3-Clause
  battery_info: ^1.0.8 # MIT
  managed_configurations:  # MIT
    git:
      url : https://github.com/mwaylabs/flutter-managed-configuration
      ref : master

  #Referenced Packages
  uuid: ^4.1.0
  path: ^1.8.1
  audio_session: ^0.1.16
  intl: ^0.18.0
  stream_transform: ^2.0.0

dependency_overrides: 
  http: ^1.1.0 # BSD-3-Clause
  uuid: ^4.1.0


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: any
  test: any
  mockito: ^5.4.2
  flutter_oss_licenses: ^2.0.1
  pigeon: ^10.0.0

  #Generators
  freezed: ^2.2.0 # MIT
  json_serializable: any # BSD-3-Clause
  flutter_gen_runner: ^5.2.0  # MIT
  built_value_generator: ^8.4.1    # BSD

  #Linter
  flutter_lints: any    # BSD-3-Clause

flutter_gen:
  output: lib/gen/
  line_length: 120

  integrations:
    flutter_svg: true